### ISSUE TITLE
Automatically look for spelling changes for all columns?

### ISSUE THREAD

**Issue by ligon** [ligon/LSMS_Library#49]
We define a method to create a dataframe `foo` with columns or indices `i,t,a,b`.

Why not *automatically* look in categorical_mappings.org for a mapping to transform these variables as needed?

Say we have in `categorical_mapping.org`:

```
#+name: a
| Label | Preferred Label |
|-----------------------------------|
| LMSM | LSMS                 |
| Libary | Library              |
```

Then something like `ll.Country('Erehwon').foo()` would automatically replace values LMSM in column A.

Or, alternatively, specify a remapping in the yaml file?  Something like:

```
foo:
  a:
     - h1aw
     - categorical_mapping: a
```

**Comment by cefayefang** [comment]
YAML supports list-format data like ['a', 'b', 'c'].
I’m thinking of adding a new feature called categorical_mapping, which would store a list of columns that have corresponding same-named categorical mapping tables in the org and should be mapped to their values.

```
cluster_features:
    file: ehcvm_conso_mli2021.dta
    idxvars:
        v: grappe
    myvars:
        Region: region
        Rural: milieu
   categorical_mapping: ['v', 'Region']
```

**Comment by ligon** [comment]
I don't see why we want to treat functions used as mappings differently from dictionaries we might look up in categorical mappings.  

And if I understand correctly, we're *already* implicitly calling mappings based on variable names.   For example, for Mali/2014-15 we have:

```
interview_date:
    file: 
        - EACICONTROLE_p1.dta
        - EACICONTROLE_p2.dta
    idxvars:
        v: grappe
        i:
            - grappe
            - menage
    myvars:
        Int_t: 
            - s00q22y
            - s00q22m
            - s00q22j
    converted_categoricals: False
```

This (i) concatenates two files, then (ii) calls a mapping `Int_t` to construct a *variable* named `Int_t`, right?
And we first look for this mapping locally (in 2014-15.py), and then if it's not found there look in Mali/_/mali.py?   And if not there do we look in LSMS_Library/_/transformations.py?

If this is right, this is analogous to what get_categorical_mapping does with categorical_mapping.org files.

**Comment by cefayefang** [comment]
I see what you mean. In your example, constructing Int_t requires a formatting function defined in 2014-15.py, which is used in the `df_data_grabber` function:
```
def Int_t(value):
    '''
    Formatting interview date
    ''' 
    # date = f'{value[0]}-{value[1]}-{value[2]}'
    date = f'{int(value[0])}-{int(value[1])}-{int(value[2])}'
    return pd.to_datetime(date, format='%Y-%m-%d', errors='coerce').date()
```

Similarly, when we want to apply categorical_mapping to certain variables, we could define formatting functions for them within  `df_data_grabber`. For example, if we want to map values for the column `food_name`, we could define a function named after the column in wave.py or country.py:

```
def food_name(value):
   return get_categorical_mapping(value)
```

This implies I should implement a `get_categorical_mapping` function that takes an input value and returns the corresponding mapped value, provided a matching mapping table exists in the categorical_mapping.org files.

For a more advanced setup, when parsing a standard YAML file (like in your example), the logic could be extended to automatically check if a mapping table with the same name as the column exists in categorical_mapping.org — and if so, apply the mapping.

However, for cases where the mapping table has a different name than the column (e.g., a mapping table named "harmonized food" used for a column named 'j'), we would need to explicitly define the mapping in the YAML file so the function knows what table to look for:

```
#Mali/2012-22/_/data_info.yml
food_acquired:
    file: s07b_me_mli2021.dta
    idxvars:
        j: 
            - s07bq01
            - categorical_mapping: 'harmonized food'

```
